apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mern-server
  template:
    metadata:
      labels:
        app: mern-server
    spec:
      containers:
      - name: mern-server
        image: chrayef/mern-server:latest
        ports:
        - containerPort: 9000
        envFrom:
        - configMapRef:
            name: app-configmap
